export const DATA = {
  name: 'Raj Patel',
  initials: 'RP',
  role: 'Full-Stack Developer & AI/ML Engineer',
  tagline: 'I build intelligent web systems that solve real problems.',
  bio: 'Passionate full-stack developer and AI/ML engineer with expertise in React, Node.js, Python, and modern web technologies. I love creating intuitive, dynamic web applications and intelligent systems that solve real-world problems.',
  location: 'Vadodara, Gujarat, India',
  email: 'rajpatel63516@gmail.com',
  github: 'https://github.com/rajpatel637',
  linkedin: 'https://linkedin.com/in/rajpatel6373',
  twitter: '',
  cv: '/Raj_Patel_Resume.pdf',

  education: {
    degree: 'B.Tech - Computer Science and Engineering',
    institute: 'Parul Institute of Engineering and Technology, Vadodara',
    period: '2022 - 2026',
    cgpa: '7.42 CGPA',
    coursework: ['DSA', 'OS', 'DBMS', 'Machine Learning', 'Computer Networks', 'System Design'],
  },

  skills: [
    { name: 'Python / AI-ML', level: 90 },
    { name: 'React / Next.js', level: 88 },
    { name: 'FastAPI / Node.js', level: 86 },
    { name: 'PostgreSQL / pgvector', level: 84 },
    { name: 'LangGraph / LangChain', level: 82 },
    { name: 'TypeScript / JavaScript', level: 85 },
    { name: 'Docker / DevOps', level: 78 },
    { name: 'Three.js / Motion UI', level: 74 },
  ],

  orbs: [
    'Python', 'C++', 'C', 'JavaScript', 'TypeScript', 'SQL',
    'React', 'Next.js', 'Three.js', 'Tailwind', 'Redux', 'Zustand',
    'FastAPI', 'Node.js', 'Express', 'WebSocket', 'JWT',
    'LangGraph', 'LangChain', 'Groq', 'Gemini', 'Llama', 'pgvector',
    'PostgreSQL', 'MongoDB', 'MySQL', 'Redis', 'Docker', 'Git',
  ],

  projects: [
    {
      num: '01',
      name: 'NexusAI',
      title: 'Production-Grade Multi-Agent AI Platform',
      period: 'Apr 2025 - Jun 2025',
      desc: 'Multi-agent AI platform automating complex coding workflows from research to code generation, debugging, and review with real-time execution and Human-in-the-Loop control.',
      stack: ['Next.js 16', 'React 19', 'FastAPI', 'LangGraph', 'Groq', 'PostgreSQL', 'Redis', 'Docker'],
      github: 'https://github.com/Rajpatel637/NexusAI',
      color: '#C6FF00',
    },
    {
      num: '02',
      name: 'RAG Document Intelligence',
      title: 'Production-Grade RAG API Platform',
      period: 'Feb 2025 - Mar 2025',
      desc: 'Scalable document intelligence API for semantic search over uploaded files with HNSW indexing, dual vector stores, async batch embeddings, and pluggable AI providers.',
      stack: ['Python', 'FastAPI', 'LangChain', 'pgvector', 'MongoDB Atlas', 'Docker', 'JWT'],
      github: 'https://github.com/Rajpatel637/RAG-Document-Intelligence',
      color: '#00FFB2',
    },
    {
      num: '03',
      name: 'AI Resume & Job Matcher',
      title: 'Full-Stack AI Job Search Platform',
      period: 'Jul 2025 - Aug 2025',
      desc: 'AI platform that parses resumes, extracts skills with NLP, scrapes live job listings, and ranks opportunities using cosine similarity with match percentages.',
      stack: ['Python', 'FastAPI', 'React.js', 'NLP', 'TF-IDF', 'Gemini', 'PostgreSQL'],
      github: 'https://github.com/Rajpatel637/AI-Resume-Job-Matcher',
      color: '#00EEFF',
    },
    {
      num: '04',
      name: 'Movieplex',
      title: 'Movie Discovery Platform',
      desc: 'Movie discovery platform with search, trending, popular and upcoming browsing, trailers, cast information, and genre filtering.',
      stack: ['React.js', 'JavaScript', 'TMDB API', 'CSS3', 'React Router', 'Axios'],
      live: 'https://movieplex-one.vercel.app/',
      github: 'https://github.com/Rajpatel637/Movieplex',
      color: '#FF9500',
    },
    {
      num: '05',
      name: 'UniEats',
      title: 'University Food Delivery System',
      desc: 'Food delivery platform for university campuses with campus delivery zones, order management, and user authentication.',
      stack: ['React.js', 'Node.js', 'Express.js', 'MongoDB', 'JavaScript', 'CSS3'],
      github: '',
      status: 'In Progress',
      color: '#FF5C8A',
    },
  ],

  timelineLabel: 'EDUCATION',
  timelineHeading: 'ACADEMIC PATH',
  experience: [
    {
      company: 'Parul Institute of Engineering and Technology',
      role: 'B.Tech - Computer Science and Engineering',
      period: '2022 - 2026',
      desc: 'CGPA: 7.42. Coursework includes DSA, Operating Systems, DBMS, Machine Learning, Computer Networks, and System Design.',
    },
    {
      company: 'AI/ML Engineering Focus',
      role: 'Applied LLM and RAG Systems',
      period: '2025',
      desc: 'Built production-style AI systems using LangGraph, LangChain, Groq, Gemini, HuggingFace embeddings, pgvector, Redis, and FastAPI.',
    },
    {
      company: 'Full-Stack Product Development',
      role: 'React, Node.js, FastAPI, and Databases',
      period: '2024 - 2025',
      desc: 'Developed modern web applications with authentication, REST APIs, WebSockets, PostgreSQL, MongoDB, Redis, Docker, Vercel, and Render.',
    },
  ],
};
